<?php

$email = $_REQUEST["email"];

include 'DBConfig.php';
$query = "SELECT * FROM merchants where Email='" . $email . "' limit 1";
$result = mysqli_query($con, $query);
$row = mysqli_fetch_array($result);
if (null != $row) {
    $activationCode = $row['ActivationCode'];
    $to = $email;
    $subject = "Reset password";
    $message = "Dear user, \nClick on the link below to recover your password.";
    $message = $message . "http://geekyntechy.com/atc/cd/web/resetPasswordForm.php?email=$email&code=$activationCode";
    $message = $message . "\n<Auto-generated e-mail, please, do not reply>";
    $from = "CityDeals";
    $headers = "From:" . $from;
//    echo $message;
    mail($to,$subject,$message,$headers);
    echo "1";
} else {
    echo "0";
}

mysqli_close($con);
?>
<?php

function get_rand_numbers($length) {
    if ($length > 0) {
        $rand_id = "";
        for ($i = 1; $i <= $length; $i++) {
            mt_srand((double) microtime() * 1000000);
            $num = mt_rand(0, 9);
            $rand_id .= $num;
        }
    }
    return $rand_id;
}

?>