
<?php
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');
$Validflag = 0;
session_start();
$captchaCode = $_SESSION['captcha']['code'];
$reply = array();
if (empty($_POST["regEmail"])) {
    $Validflag = 1;
} else {
    $email = $_POST["regEmail"];
}

if (empty($_POST["regPassword"])) {
    $Validflag = 1;
} else {
    $password = $_POST["regPassword"];
}

if (empty($_POST["regCPassword"])) {
    $Validflag = 1;
} else {
    $confirmPassword = $_POST["regCPassword"];
}

if (empty($_POST["regMobileno"])) {
    $Validflag = 1;
} else {
    $cellNo = $_POST["regMobileno"];
}

if (empty($_POST["captcha"])) {
    $Validflag = 1;
} else {
    $captcha = $_POST["captcha"];
}

if ($Validflag == 1) {
    $reply['status'] = "incomplete";
} else if ($password != $confirmPassword) {
    $reply['status'] = "password";
} else if($captcha != $captchaCode){
    $reply['status'] = "captcha";
}else {

    include 'DBConfig.php';
    $query = "SELECT * FROM merchants where Email='" . $email . "' limit 1";
    $result = mysqli_query($con, $query);
    if (null != mysqli_fetch_array($result)) {
        mysqli_close($con);
        $reply['status'] = "signup0";
    } else {

        $activationCode = get_rand_numbers(32);
        mysqli_query($con, "INSERT INTO merchants (Email, Password, ContactNumber, Status, ActivationCode,Balance) VALUES ('$email','$password','$cellNo',0,'$activationCode',0)");
        //mysqli_query($con, $query);
        mysqli_close($con);

        $to = $email;
        $subject = "Confirm your email at CityDeals.com";
        $message = "Dear user, \nThankyou very much for registering with CityDeals.com. Please click on the link below to complete you registration.";
        $message = $message . "http://geekyntechy.com/atc/cd/web/completeRegistration.php?email=$email&code=$activationCode";
        $message = $message . "\n<Auto-generated e-mail, please, do not reply>";
        $from = "CityDeals";
        $headers = "From:" . $from;
        mail($to, $subject, $message, $headers);
        $reply['status'] = "signup1";
    }
}

echo json_encode($reply);
?>

<?php

function get_rand_numbers($length) {
    if ($length > 0) {
        $rand_id = "";
        for ($i = 1; $i <= $length; $i++) {
            mt_srand((double) microtime() * 1000000);
            $num = mt_rand(0, 9);
            $rand_id .= $num;
        }
    }
    return $rand_id;
}
?>
